/**
 * LaTeX resume generator for simohakim.com.
 *
 * Renders one resume.<lang>.tex per language from the same data.json that
 * builds the site, in the moderncv/banking format with the \customcventry and
 * \customcvproject macros.
 *
 * Run: node tools/build-resume.mjs      (from the repo root)
 */
import fs from 'node:fs';
import path from 'node:path';
import { L, t, languagesIn } from './i18n.mjs';

const root = path.resolve('.');
const data = JSON.parse(fs.readFileSync(root + '/data.json', 'utf8'));
const DEFAULT_LANG = data.defaultLanguage || 'en';
const LANGS = languagesIn(data);
if (!LANGS.includes(DEFAULT_LANG)) LANGS.unshift(DEFAULT_LANG);

/* ------------------------------------------------------------------ escaping */
/** Escape the characters TeX treats as markup. Order matters: backslash first. */
const tex = (s = '') =>
  String(s)
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([&%$#_{}])/g, '\\$1')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');

/**
 * Split a paragraph of prose into one bullet per sentence. The lookbehind
 * requires a word character before the period, so initials such as
 * "Arthur C. Clarke" or ".NET 8." don't start a new bullet.
 */
const sentences = (text = '') =>
  text
    .split(/(?<=[a-z0-9)][.!?])\s+(?=[A-ZÀ-ÖØ-Þ(])/)
    .map((s) => s.trim())
    .filter(Boolean);

/**
 * Entry body: a single sentence stays inline, anything longer becomes an
 * itemize block.
 */
const body = (text) => {
  const items = sentences(text);
  if (!items.length) return '';
  if (items.length === 1) return tex(items[0]);
  return `{
    \\begin{itemize}
${items.map((s) => `        \\item ${tex(s)}`).join('\n')}
    \\end{itemize}
  }`;
};

const shown = (rows) => rows.filter((r) => (r.showInResume ?? 'Y').toUpperCase() === 'Y');

function render(lang) {
  const s = t(lang);
  const l = (v) => L(v, lang, DEFAULT_LANG);
  const me = data.personalInfo;
  const social = data.socialLinks;

  /**
   * data.json keeps "Company, City, PR" in one field because that is what the
   * website prints; the resume macro wants them apart.
   */
  const splitOrg = (company = '') => {
    const m = company.match(/^(.*),\s*([^,]+,\s*[A-Za-z]{2})\s*$/);
    return m ? { org: m[1].trim(), where: m[2].trim() } : { org: company.trim(), where: l(me.contact.location) };
  };

  const education = shown(data.education)
    .map((e) => {
      const where = l(e.location) || l(me.contact.location);
      return `\\customcventry{${tex(e.year)}}{${tex(`${l(e.degree)} — ${l(e.field)}`)}}{${tex(
        l(e.institution)
      )}}{${tex(where)}}{}{}`;
    })
    .join('\n');

  const work = shown(data.workExperience)
    .map((w) => {
      const { org, where } = splitOrg(l(w.company));
      return `\\customcventry{${tex(w.years)}}{${tex(l(w.position))}}{${tex(org)}}{${tex(where)}}{}{${body(
        l(w.resumeDetails) || l(w.details)
      )}}`;
    })
    .join('\n\n');

  const projects = data.projects
    .map((p) => {
      /* A project with a `link` gets a clickable title in the PDF. */
      const name = p.link ? `\\href{${p.link}}{${tex(l(p.name))}}` : tex(l(p.name));
      return `\\customcvproject{${name}}{}{${body(l(p.description))}}`;
    })
    .join('\n');

  const skills = [
    [s.resume.programming, data.resumeSkills?.programming],
    [s.resume.data, data.resumeSkills?.data],
    [s.resume.misc, data.resumeSkills?.miscellaneous],
  ]
    .filter(([, list]) => list?.length)
    .map(([label, list]) => `\\textbf{${tex(label)}:} ${list.map(tex).join(', ')}`)
    .join('\\\\\n');

  return `%% GENERATED by tools/build-resume.mjs from data.json — do not edit by hand.
%% Language: ${lang}
\\documentclass[11pt,a4paper,roman]{moderncv}
\\moderncvstyle{banking}
\\moderncvcolor{blue}
\\nopagenumbers{}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
% Charger FontAwesome5 pour les icônes
\\usepackage[scale=0.92]{geometry}
\\usepackage{color}
\\newcommand*{\\customcventry}[7][.25em]{
  \\begin{tabular}{@{}l}
    {\\bfseries #4}
  \\end{tabular}
  \\hfill
  \\begin{tabular}{l@{}}
    {\\bfseries #5}
  \\end{tabular}\\\\
  \\begin{tabular}{@{}l}
    {\\itshape #3}
  \\end{tabular}
  \\hfill
  \\begin{tabular}{l@{}}
    {\\itshape #2}
  \\end{tabular}
  \\ifx&#7&
  \\else{
    \\begin{minipage}{\\maincolumnwidth}
      \\footnotesize #7
    \\end{minipage}}
  \\fi
  \\par\\addvspace{#1}
}
\\newcommand*{\\customcvproject}[4][.25em]{
  \\begin{tabular}{@{}l}
    {\\small\\bfseries #2}
  \\end{tabular}
  \\hfill
  \\begin{tabular}{l@{}}
    {\\footnotesize\\itshape #3}
  \\end{tabular}
  \\ifx&#4&
  \\else{
    \\begin{minipage}{\\maincolumnwidth}%
      \\footnotesize #4
    \\end{minipage}}
  \\fi
  \\par\\addvspace{#1}
}
\\setlength{\\tabcolsep}{12pt}

\\name{${tex(me.surname)}}{${tex(me.lastname)}}
\\address{${tex(l(me.contact.address))}}

\\begin{document}
\\makecvtitle
\\vspace*{-13mm}
\\begin{center}
\\begin{tabular}{ c c c c c }\\faLanguage\\enspace ${tex(
    l(me.languages)
  )}& \\faEnvelope\\enspace ${tex(me.contact.email)}& \\href{${social.linkedin}}{\\faLinkedin} & \\href{${
    social.github
  }}{\\faGithub} & \\faMobile\\enspace ${tex(me.contact.phone)} \\\\
  \\end{tabular}
\\end{center}

\\section{${tex(s.resume.about)}}
${tex(l(data.resumeSummary) || l(data.about.description))}

\\section{${tex(s.resume.skills)}}
${skills}

\\section{${tex(s.resume.education)}}
${education}

\\section{${tex(s.resume.work)}}

${work}

\\break

\\section{${tex(s.resume.projects)}}
${projects}
\\end{document}
`;
}

for (const lang of LANGS) {
  fs.writeFileSync(path.join(root, `resume.${lang}.tex`), render(lang), 'utf8');
}

console.log(
  `resume tex written — ${LANGS.map((c) => `resume.${c}.tex`).join(', ')} ` +
    `(${shown(data.education).length} education, ${shown(data.workExperience).length} roles, ${
      data.projects.length
    } projects)`
);
